# a=input("Users name: ")
# print(len(a))

str=("$Hi. I am the $first chapter of python programming language$")
print(str.count("$"))
print(str.replace("$","#"))
print(str.find("first"))
print(str.split(" "))
print(str.upper())
print(str.endswith("language$"))
print(str.startswith("$Hi"))
print(str.isalnum())
print(str.isalpha())
print(str.capitalize())